Application design
sologubd/react-notes pull request #1
Opened 2022-01-26 19:29 UTC by sologubd

Base application components - Nvagation, Note, NoteList

2022-01-26 20:53 UTC, Rastopyr requested changes
Я бы хотел еще тебя попросить немного детализировать описание ПР :)

Можно использовать советы из [гайда который я скидывал в Slack](https://oumaima-dahhoum.medium.com/how-to-create-a-good-pull-request-with-examples-and-templates-cfc92f2bb94e).

Или же можно использовать шаблон из трех вопросов.
1) Что? - Что именно содержит этот ПР? какую задачу он решает?
2) Как? - Как конкретно решается выше описанная задача? 
3) Почему? - Почему используется именно это решение? Почему оно наиболее оптимальное?

Спасибо!

2022-01-26 20:53 UTC, Rastopyr commented on public/css/main.css
> +  padding: 10px; }
В других местах ти используешь rem а тут px. Выглядит не очень консистентно. Может тут тоже получится использовать rem?

2022-01-26 20:53 UTC, Rastopyr commented on public/css/main.css
> +section.note {
Вижу что в некоторых местах используется один и тот же class-name, я бы предложил сделать имена классов более уникальными, и отказаться от селектора элемента?

2022-01-26 20:53 UTC, Rastopyr commented on public/css/main.css
> +div {
Давай дадим элементу дива какой то класс, и будем вместо `div` использовать имя этого css-класса

2022-01-26 20:53 UTC, Rastopyr commented on src/App.tsx
> +class App extends React.Component {
Тут вместо класса компонента стоит использовать function component

2022-01-26 20:53 UTC, Rastopyr commented on src/components/navigation.tsx
> +class NotesNavbar extends React.Component {
Тут вместо класса компонента стоит использовать function component

2022-01-26 20:53 UTC, Rastopyr commented on src/components/note.tsx
> +class Note extends React.Component<NotesProps> {
Тут вместо класса компонента стоит использовать function component

2022-01-26 20:53 UTC, Rastopyr commented on src/components/note.tsx
> +            {this.props.title}
Я правильно понял что это пока заглушка UI, а логику ты напишешь отдельным PR?

2022-01-27 10:34 UTC, sologubd commented on public/css/main.css
> +  padding: 10px; }
Done

2022-01-27 10:34 UTC, sologubd commented on public/css/main.css
> +div {
Done

2022-01-27 16:02 UTC, Rastopyr requested changes

2022-01-27 16:02 UTC, Rastopyr commented on src/components/note-form.tsx
> +    setMode(Mode.VIEW);
Тут может быть другой Mode? Предлагаю пропсу назвать goToMainView и имплементацию определить уровнем выше.

Компонент станет более независимым, и меньше логики будет внутри. Плюс честнее будет контракт компонента

2022-01-27 16:18 UTC, merged