Note editing functionality
sologubd/react-notes pull request #2
Opened 2022-01-29 12:52 UTC by sologubd

- Title validation. Title cannot be empty
- Text validation. Text cannot exceed 1000 characters.
- Removing a selected note
- Displaying selected note
- A few CSS fixes

Editing notes will be implemented in the next PR.

2022-01-30 13:29 UTC, nadiia-kobylinska commented on src/components/notes-list.tsx
> +            <section id={`${id}`} key={`${id}`} className={`section is-small note-list-item ${selected}`}
А зачем тут id для секции? 
И думаю `${id}` можно заменить на просто `id`

2022-01-30 13:29 UTC, nadiia-kobylinska commented on src/components/notes-list.tsx
> +          const selected = (selectedNoteId == id) ? "selected" : ""
в большинстве случаем лучше использовать `===` вместо `==` для более строго сравнения, так можно быть уверенным в в возвращаемом значении

2022-01-30 13:29 UTC, nadiia-kobylinska commented on src/App.tsx
> +      notes.splice(selectedNoteId, 1);
`splice` с реактом не очень хорошо дружит. Из-за него не обновляется state и список заметок не перерисовывается. 
Можно создать новый массив или использовать `slice`

2022-01-30 13:39 UTC, sologubd commented on src/App.tsx
> +    window.localStorage.setItem("notes", JSON.stringify(updatedNotes));
так, я вирішив не чіпати поки. бо мій проект я видалив і пишу з нуля наздоганяючи домашки ) виправлю в наступній ітерайції

2022-01-30 14:00 UTC, nadiia-kobylinska approved these changes

2022-01-30 14:57 UTC, Rastopyr requested changes

2022-01-30 14:57 UTC, Rastopyr commented on src/App.tsx
> +const getNotes = () => {
Стоит указать тип возвращаемый

2022-01-30 14:57 UTC, Rastopyr commented on src/App.tsx
> +const getNotes = () => {
Здорово что вынес в отдельную функцию!

2022-01-30 14:57 UTC, Rastopyr commented on src/components/note-form.tsx
Эти стейты тут не нужны. Они только усложняют логику компонента.

Смотри, есть какие то правила валидации которые пересчитываются, если меняется `title`, `setTitile`. Правила валидации не должны дополнительно форсировать рендеринг(по крайней мере в этом компоненте).

Давай попробуем начать с того, что нужно определить две переменные, которые называются `isTitleValid`, `isDescriptionValid`. Как они будут обсчитываться?

2022-01-30 14:57 UTC, Rastopyr commented on src/components/note-form.tsx
> +  const validateTitle = (value: string) => {
Будет круто если эти функции будут вне компонента NoteForm. Единственное от чего оно зависит это setter для стейта, но выше есть коммент с предложением его убрать.

2022-01-30 14:57 UTC, Rastopyr commented on src/components/notes-list.tsx
> +              onClick={() => {showNote(id)}}
nit: `onClick={() => showNote(id)}`

2022-01-30 15:44 UTC, sologubd commented on src/components/note-form.tsx
В нашому випадку буде що по типу
`const isTitleValid  = title.length > 0;`
`isDescriptionValid = text.length <= 1000;`
Я розумію що можна валідувати без використання state, але моя ідея була в тому, що при наявності кількох правил валідації, наприклад, title не більше за 100 символів, буде відображатися кілька помилок. Але ідею я зрозумів, можна винести окремо все в якист об'єкт по типу
`type titleValid = { valid: boolean, errors: string[] }`
і jsx:
`{titleValid.errors.map((err: string, key: number) => <p key={key} className="help is-danger">`
Що думаєш?

2022-01-30 16:43 UTC, sologubd commented on src/components/note-form.tsx
```
const isTitleValid = title.length > 0;
const isDescriptionValid = text.length <= 1000;
```

2022-01-30 17:48 UTC, sologubd commented on src/components/note-form.tsx
Я повністю погоджуюся що валідація не має тригерити рендер, і її можна повністю винести.

Моя ідея була в тому, щоб не показувати помилки на самому початку, а тільки якщо:
- був сабміт і форма не валідна (при цьому користувач може натиснути на кнопки не ввіши жодних даних в поля форми)
- користувач почав вводити дані і спрацбвала якась валідація
А також показивати список помилок, якщо буде порушено кілька пунктів валідації, наприклад title не пустий і не перевищує 100 символів.

2022-01-31 07:59 UTC, sologubd commented on src/components/note-form.tsx
Я спробував реалізувати задумку [в останньому коміті](https://github.com/sologubd/react-notes/pull/2/commits/2e2363bb9114c1e48f8f135cb7dd1f7660f28dd9)

Якщо показувати всі помилки валідації одразу, то взагалі все що стосується валідації можна роюити без використання state і в ньому будуть тільки title і text

2022-01-31 10:44 UTC, Rastopyr approved these changes

2022-01-31 10:51 UTC, merged