Using useContext and useReducer
sologubd/react-notes pull request #3
Opened 2022-01-31 17:22 UTC by sologubd

- Вся логіка винесена за межі React компонентів і працює через контекст
- state management винесений за межі компонентів і імплементований через useReducer
- функції для роботи з БД (local storage) винесені в окремий модуль
- створені типи івентів для списку нотатків
- створені типи івентів для view mode
- стиорені хендлери для упраивління нотатками  (видалення/стиворення/перегляд)
- стиорений хендлер для зміни view (view/edit)

2022-02-01 11:40 UTC, olhakhomyak approved these changes

2022-02-01 12:12 UTC, nadiia-kobylinska requested changes

2022-02-01 12:12 UTC, nadiia-kobylinska commented on src/components/navigation.tsx
> +              <span className="icon is-medium" onClick={goToMainView}>
Все виглядає читабельно і логічно, єдине що впало в очі це назва `goToMainView`, попередня здавалась більш логічною

2022-02-01 14:55 UTC, Rastopyr requested changes

2022-02-01 14:55 UTC, Rastopyr commented on src/components/navigation.tsx
> +  const addNote = () => actions.changeView(Mode.EDIT);
Я бы предложил использовать более специальные хуки, например `useNoteActions`/`useNoteState`

2022-02-01 14:55 UTC, Rastopyr commented on src/context.ts
> +export const NotesState = () => {
для хуков используется нотация `use<WhatEver>`, например `useNoteContext`

2022-02-01 14:55 UTC, Rastopyr commented on src/context.ts
> +export const NotesContext = React.createContext<[NotesListState, Dispatcher]>([initialState, () => undefined]);
Вместо Undefined я бы предложил использовать паттерн Null Object.


https://refactoring.guru/introduce-null-object

2022-02-01 14:55 UTC, Rastopyr commented on src/note-reducer.ts
> +        saveNotes(notes);
Я бы такой sideEffect не добавлял в reducer. иначе reducer не постетируешь без браузера.

2022-02-01 14:55 UTC, Rastopyr commented on src/note-reducer.ts
> +        ...state,
Кажется что блок можно заменить на `return state`. И поменять условие местами
```
if (state.selectedNoteId !== null) {
  return state
}
````

2022-02-01 14:55 UTC, Rastopyr commented on src/note-reducer.ts
> +        notes.splice(state.selectedNoteId, 1);
Я бы предложил использовать immutable подход без splice.

2022-02-01 20:23 UTC, sologubd commented
@Rastopyr 
Помістив `saveNotes()` в `useNoteState`, використав `useEffect`.
Мені здається, що це місце підходить.

2022-02-01 21:18 UTC, nadiia-kobylinska approved these changes

2022-02-02 10:04 UTC, Rastopyr requested changes

2022-02-02 10:04 UTC, Rastopyr commented on src/components/note.tsx
> +  const note = state.selectedNoteId !== null ? state.notes[state.selectedNoteId] : NullNote;
За что цепляется глаз, что логика редактирования заметки немного размазана по слоям.

- внутри компонента
- в интеграционном слое
- а данные берутся из стейта

Если обобщить эту логику в стейте другой модельки, то NullNote вообще не потребуется и сильно разгрузится логика компонента `Note`.

2022-02-02 10:13 UTC, Rastopyr commented on src/components/note.tsx
> +  const note = state.selectedNoteId !== null ? state.notes[state.selectedNoteId] : NullNote;
Ще краще назвати цей компонент `NoteForm`

2022-02-02 10:29 UTC, sologubd commented on src/components/note.tsx
> +  const note = state.selectedNoteId !== null ? state.notes[state.selectedNoteId] : NullNote;
Описав все в [issue](https://github.com/sologubd/react-notes/issues/4)

2022-02-02 22:55 UTC, Rastopyr commented on src/components/note-form.tsx
> +  const goToMainView = () => actions.changeView(Mode.VIEW);
Тут напрашивается специфический метод `goToMainView` предоставляемый сразу из actions.

2022-02-02 23:00 UTC, Rastopyr requested changes

2022-02-02 23:00 UTC, Rastopyr commented on src/context.ts
> +  notes: getNotes(),
Тут инициализируется стейт прямо при выполнении модуля. Я бы предложил перенести инициализацию в lifecycle приложения и делать это внутри NoteProvider.

И там же снепшотить стейт на измненеие. Это будет более flexible логика и сконцентрованая в одном месте.

2022-02-02 23:00 UTC, Rastopyr commented on src/components/note-form.tsx
> +  const goToMainView = () => actions.changeView(Mode.VIEW);
Тут напрашивается специфический метод goToMainView предоставляемый сразу из actions.

2022-02-02 23:00 UTC, Rastopyr commented on src/components/navigation.tsx
> +  const addNote = () => actions.changeView(Mode.EDIT);
Тут напрашивается специфический метод goToEditView предоставляемый сразу из actions.

2022-02-03 10:13 UTC, Rastopyr approved these changes
Небольшой request to change, но это уже на твое усмотрение

2022-02-03 10:13 UTC, Rastopyr commented on src/App.tsx
> +  const storedNotes = getNotes();
`useState(() => getNotes())`

Инициализируем один раз)

2022-02-03 15:58 UTC, merged