The application uses a few contexts
sologubd/react-notes pull request #5
Opened 2022-02-16 15:25 UTC by sologubd

- **Додана форма логіна**
Форма логіна фейкова, зберігає в localStorage `bollean` значення. 
Логіка роботи наступна:
1. Якщо значення нема або користувач "не аутентифікований" то показується сторінка логіна
2. Якщо користувач "аутентифікований", то показується список нотатків
3. Якщо користувач виконує "sign-out" то значення в localStorage міняється і користувач потрапляє на сторінку логіна

- **Логіка, що визначає, яку View показувати винесена в окремий state**

- **Логіка роботи форми для додавання нотатків винесена в окремий state**
Єдиний хендлер, що залишився поза контекстом для робльи форми - `submit`, оскільки він використовує інші контексти.

2022-02-16 15:54 UTC, iamr0man commented on src/components/auth.tsx
> +    login();
я наверное создал бы контекст auth и определил там состояние + экшины

2022-02-17 16:40 UTC, Rastopyr requested changes

2022-02-17 16:40 UTC, Rastopyr commented on src/components/main.tsx
> +  readonly view: View;
давай назовем как то более осмысленно. например ViewMode

2022-02-17 16:40 UTC, Rastopyr commented on src/components/note-form.tsx
> +const NoteFormConsumer: React.FC = () => {
Я бы его назвал `NoteForm` просто)
Провайдер мне кажется стоит переместить в файл на более высокий уровень

2022-02-17 16:40 UTC, Rastopyr commented on src/components/note-form.tsx
> +      viewActions.goToNotesView();
Давай еще в следующем ПР попробуем как то унифицировать эту логику на более выскором уровне?

2022-02-19 12:47 UTC, sologubd commented on src/components/note-form.tsx
> +const NoteFormConsumer: React.FC = () => {
готово

2022-02-19 12:54 UTC, sologubd commented on src/components/main.tsx
> +  readonly view: View;
зроблено

2022-02-19 12:59 UTC, sologubd commented
@Rastopyr All changes are addressed in the latest commit.

2022-02-22 15:19 UTC, merged